version: '3'
services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=pasword
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/var/www/app
    working_dir: /var/www/app
    ports:
      - "8080:8080"
    depends_on:
      - db